# Generated by Django 5.2.5 on 2025-08-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.CharField(blank=True, max_length=30, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=300)),
                ('autor', models.CharField(blank=True, max_length=200, null=True)),
                ('publicadora', models.CharField(blank=True, max_length=100, null=True)),
                ('data_publicacao', models.DateField(blank=True, null=True)),
                ('numero_paginas', models.IntegerField(blank=True, null=True)),
                ('capa', models.TextField(blank=True)),
                ('sinopse', models.TextField(blank=True)),
                ('categoria', models.CharField(blank=True, max_length=200, null=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
    ]
