# Generated by Django 5.2.5 on 2025-08-24 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Pendente'), (2, 'Pago'), (3, 'Cancelado')], default=1)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Itens_Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_livro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.livro')),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_pedidos', to='pedido.pedido')),
            ],
        ),
    ]
