# Generated by Django 5.2.5 on 2025-08-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itens_pedidos',
            name='titulo_livro',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
